services:
  cube:
    build: ./cube
    environment:
      - CUBEJS_DB_HOST=clickhouse
      - CUBEJS_DEV_MODE=true
    ports:
      - 3002:4000

  clickhouse:
    image: yandex/clickhouse-server:21.3
    ports:
      - 8123
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./ingest:/app
      - ./ingest/data/stations:/var/lib/clickhouse/user_files/stations
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse-data: